### ISSUE TITLE
Is it possible to add shortcuts to left and right?

### ISSUE THREAD

**Issue by pablo-sg-pacheco** [sanketkheni01/Windows-11-Virtual-desktop-animation#5]
Hi, 

First of all, thanks for this.

I noticed you have added the shortcuts up and down to use the animations. Is it possible to add the shortcodes left and right? Examples:

- To Left workspace: <kbd>Win</kbd>+<kbd>Ctrl</kbd>+<kbd>←</kbd>

- To Right workspace: <kbd>Win</kbd>+<kbd>Ctrl</kbd>+<kbd>→</kbd>

**Comment by sanketkheni01** [comment]
Thank you for the suggestion. However, at this time, it is not possible to override the default Windows shortcut as doing so may trigger the default behavior. Rest assured that I will definitely look into it.
