### ISSUE TITLE
application does not start automatically when the window restarts

### ISSUE THREAD

**Issue by cug-auto-zp** [sanketkheni01/Windows-11-Virtual-desktop-animation#7]
I used the .exe you provided, but the application does not start automatically when the window restarts, why is this?
How do you solve it?

**Comment by TheFatherMind** [comment]
Right click on start and select "Run" then in the box type "Shell:Startup" with no quotes.  Press OK.  That will open your startup folder.  Put a shortcut to the program in that folder... you can right click on the EXE and choose "Copy" then switch to the startup folder you opened, right click in a blank area and choose "Paste Shortcut".

**Comment by cug-auto-zp** [comment]
Thank you send E-mail to me.l am busy in studying .lf l read it,l will reply you  the first time.

**Comment by cug-auto-zp** [comment]
> Right click on start and select "Run" then in the box type "Shell:Startup" with no quotes. Press OK. That will open your startup folder. Put a shortcut to the program in that folder... you can right click on the EXE and choose "Copy" then switch to the startup folder you opened, right click in a blank area and choose "Paste Shortcut".

Thank you so much for your reply Tried it and it worked
